apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: NodePort
  selector:
    name: service1-envoy
  ports:
  - name: web
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-envoy
  labels:
    app: service1-envoy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: service1-envoy
  template:
    metadata:
      labels:
        name: service1-envoy
    spec:
      containers:
      - name: service
        image: lreimer/service-envoy:v1.0.0
        command: ["python3", "/code/service.py"]
        env:
        - name: SERVICE_NAME
          value: "1"
        ports:
        - containerPort: 8080
      - name: envoy
        image: lreimer/service-envoy:v1.0.0
        command: ["envoy", "-c", "/etc/service-envoy.yaml", "--service-cluster", "service1"]
        ports:
        - containerPort: 80
      terminationGracePeriodSeconds: 10
