apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: hello-service
    version: v1.0.0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-service
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: hello-service
        version: v1.0.0
    spec:
      containers:
      - name: hello-service
        image: "hello-service:1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          timeoutSeconds: 5
