version: "2.3"

services:
  krakend-simple:
    build:
      context: .
    image: krakend-simple:v1.0.0
    mem_limit: 128m
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      - krakend

networks:
  krakend:
    driver: bridge
